/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScattergoriesRouteImport } from './routes/scattergories'
import { Route as OwnerLoginRouteImport } from './routes/owner-login'
import { Route as GmailAssistantRouteImport } from './routes/gmail-assistant'
import { Route as AlphabetRouteImport } from './routes/alphabet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScattergoriesRoomIdRouteImport } from './routes/scattergories/$roomId'
import { Route as GameRoomIdRouteImport } from './routes/game/$roomId'

const ScattergoriesRoute = ScattergoriesRouteImport.update({
  id: '/scattergories',
  path: '/scattergories',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/owner-login',
  path: '/owner-login',
  getParentRoute: () => rootRouteImport,
} as any)
const GmailAssistantRoute = GmailAssistantRouteImport.update({
  id: '/gmail-assistant',
  path: '/gmail-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphabetRoute = AlphabetRouteImport.update({
  id: '/alphabet',
  path: '/alphabet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScattergoriesRoomIdRoute = ScattergoriesRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => ScattergoriesRoute,
} as any)
const GameRoomIdRoute = GameRoomIdRouteImport.update({
  id: '/game/$roomId',
  path: '/game/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alphabet': typeof AlphabetRoute
  '/gmail-assistant': typeof GmailAssistantRoute
  '/owner-login': typeof OwnerLoginRoute
  '/scattergories': typeof ScattergoriesRouteWithChildren
  '/game/$roomId': typeof GameRoomIdRoute
  '/scattergories/$roomId': typeof ScattergoriesRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alphabet': typeof AlphabetRoute
  '/gmail-assistant': typeof GmailAssistantRoute
  '/owner-login': typeof OwnerLoginRoute
  '/scattergories': typeof ScattergoriesRouteWithChildren
  '/game/$roomId': typeof GameRoomIdRoute
  '/scattergories/$roomId': typeof ScattergoriesRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alphabet': typeof AlphabetRoute
  '/gmail-assistant': typeof GmailAssistantRoute
  '/owner-login': typeof OwnerLoginRoute
  '/scattergories': typeof ScattergoriesRouteWithChildren
  '/game/$roomId': typeof GameRoomIdRoute
  '/scattergories/$roomId': typeof ScattergoriesRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alphabet'
    | '/gmail-assistant'
    | '/owner-login'
    | '/scattergories'
    | '/game/$roomId'
    | '/scattergories/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alphabet'
    | '/gmail-assistant'
    | '/owner-login'
    | '/scattergories'
    | '/game/$roomId'
    | '/scattergories/$roomId'
  id:
    | '__root__'
    | '/'
    | '/alphabet'
    | '/gmail-assistant'
    | '/owner-login'
    | '/scattergories'
    | '/game/$roomId'
    | '/scattergories/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlphabetRoute: typeof AlphabetRoute
  GmailAssistantRoute: typeof GmailAssistantRoute
  OwnerLoginRoute: typeof OwnerLoginRoute
  ScattergoriesRoute: typeof ScattergoriesRouteWithChildren
  GameRoomIdRoute: typeof GameRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scattergories': {
      id: '/scattergories'
      path: '/scattergories'
      fullPath: '/scattergories'
      preLoaderRoute: typeof ScattergoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-login': {
      id: '/owner-login'
      path: '/owner-login'
      fullPath: '/owner-login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmail-assistant': {
      id: '/gmail-assistant'
      path: '/gmail-assistant'
      fullPath: '/gmail-assistant'
      preLoaderRoute: typeof GmailAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alphabet': {
      id: '/alphabet'
      path: '/alphabet'
      fullPath: '/alphabet'
      preLoaderRoute: typeof AlphabetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scattergories/$roomId': {
      id: '/scattergories/$roomId'
      path: '/$roomId'
      fullPath: '/scattergories/$roomId'
      preLoaderRoute: typeof ScattergoriesRoomIdRouteImport
      parentRoute: typeof ScattergoriesRoute
    }
    '/game/$roomId': {
      id: '/game/$roomId'
      path: '/game/$roomId'
      fullPath: '/game/$roomId'
      preLoaderRoute: typeof GameRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ScattergoriesRouteChildren {
  ScattergoriesRoomIdRoute: typeof ScattergoriesRoomIdRoute
}

const ScattergoriesRouteChildren: ScattergoriesRouteChildren = {
  ScattergoriesRoomIdRoute: ScattergoriesRoomIdRoute,
}

const ScattergoriesRouteWithChildren = ScattergoriesRoute._addFileChildren(
  ScattergoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlphabetRoute: AlphabetRoute,
  GmailAssistantRoute: GmailAssistantRoute,
  OwnerLoginRoute: OwnerLoginRoute,
  ScattergoriesRoute: ScattergoriesRouteWithChildren,
  GameRoomIdRoute: GameRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
