/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScattergoriesRouteImport } from './routes/scattergories'
import { Route as OwnerLoginRouteImport } from './routes/owner-login'
import { Route as GmailAssistantRouteImport } from './routes/gmail-assistant'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AlphabetRouteImport } from './routes/alphabet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as ScattergoriesRoomIdRouteImport } from './routes/scattergories/$roomId'
import { Route as GameRoomIdRouteImport } from './routes/game/$roomId'
import { Route as BooksTierBoardRouteImport } from './routes/books/tier-board'
import { Route as BooksSettingsRouteImport } from './routes/books/settings'
import { Route as BooksRecommendationsRouteImport } from './routes/books/recommendations'
import { Route as BooksLibraryRouteImport } from './routes/books/library'

const ScattergoriesRoute = ScattergoriesRouteImport.update({
  id: '/scattergories',
  path: '/scattergories',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/owner-login',
  path: '/owner-login',
  getParentRoute: () => rootRouteImport,
} as any)
const GmailAssistantRoute = GmailAssistantRouteImport.update({
  id: '/gmail-assistant',
  path: '/gmail-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphabetRoute = AlphabetRouteImport.update({
  id: '/alphabet',
  path: '/alphabet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const ScattergoriesRoomIdRoute = ScattergoriesRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => ScattergoriesRoute,
} as any)
const GameRoomIdRoute = GameRoomIdRouteImport.update({
  id: '/game/$roomId',
  path: '/game/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksTierBoardRoute = BooksTierBoardRouteImport.update({
  id: '/tier-board',
  path: '/tier-board',
  getParentRoute: () => BooksRoute,
} as any)
const BooksSettingsRoute = BooksSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BooksRoute,
} as any)
const BooksRecommendationsRoute = BooksRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => BooksRoute,
} as any)
const BooksLibraryRoute = BooksLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => BooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alphabet': typeof AlphabetRoute
  '/books': typeof BooksRouteWithChildren
  '/gmail-assistant': typeof GmailAssistantRoute
  '/owner-login': typeof OwnerLoginRoute
  '/scattergories': typeof ScattergoriesRouteWithChildren
  '/books/library': typeof BooksLibraryRoute
  '/books/recommendations': typeof BooksRecommendationsRoute
  '/books/settings': typeof BooksSettingsRoute
  '/books/tier-board': typeof BooksTierBoardRoute
  '/game/$roomId': typeof GameRoomIdRoute
  '/scattergories/$roomId': typeof ScattergoriesRoomIdRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alphabet': typeof AlphabetRoute
  '/gmail-assistant': typeof GmailAssistantRoute
  '/owner-login': typeof OwnerLoginRoute
  '/scattergories': typeof ScattergoriesRouteWithChildren
  '/books/library': typeof BooksLibraryRoute
  '/books/recommendations': typeof BooksRecommendationsRoute
  '/books/settings': typeof BooksSettingsRoute
  '/books/tier-board': typeof BooksTierBoardRoute
  '/game/$roomId': typeof GameRoomIdRoute
  '/scattergories/$roomId': typeof ScattergoriesRoomIdRoute
  '/books': typeof BooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alphabet': typeof AlphabetRoute
  '/books': typeof BooksRouteWithChildren
  '/gmail-assistant': typeof GmailAssistantRoute
  '/owner-login': typeof OwnerLoginRoute
  '/scattergories': typeof ScattergoriesRouteWithChildren
  '/books/library': typeof BooksLibraryRoute
  '/books/recommendations': typeof BooksRecommendationsRoute
  '/books/settings': typeof BooksSettingsRoute
  '/books/tier-board': typeof BooksTierBoardRoute
  '/game/$roomId': typeof GameRoomIdRoute
  '/scattergories/$roomId': typeof ScattergoriesRoomIdRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alphabet'
    | '/books'
    | '/gmail-assistant'
    | '/owner-login'
    | '/scattergories'
    | '/books/library'
    | '/books/recommendations'
    | '/books/settings'
    | '/books/tier-board'
    | '/game/$roomId'
    | '/scattergories/$roomId'
    | '/books/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alphabet'
    | '/gmail-assistant'
    | '/owner-login'
    | '/scattergories'
    | '/books/library'
    | '/books/recommendations'
    | '/books/settings'
    | '/books/tier-board'
    | '/game/$roomId'
    | '/scattergories/$roomId'
    | '/books'
  id:
    | '__root__'
    | '/'
    | '/alphabet'
    | '/books'
    | '/gmail-assistant'
    | '/owner-login'
    | '/scattergories'
    | '/books/library'
    | '/books/recommendations'
    | '/books/settings'
    | '/books/tier-board'
    | '/game/$roomId'
    | '/scattergories/$roomId'
    | '/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlphabetRoute: typeof AlphabetRoute
  BooksRoute: typeof BooksRouteWithChildren
  GmailAssistantRoute: typeof GmailAssistantRoute
  OwnerLoginRoute: typeof OwnerLoginRoute
  ScattergoriesRoute: typeof ScattergoriesRouteWithChildren
  GameRoomIdRoute: typeof GameRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scattergories': {
      id: '/scattergories'
      path: '/scattergories'
      fullPath: '/scattergories'
      preLoaderRoute: typeof ScattergoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-login': {
      id: '/owner-login'
      path: '/owner-login'
      fullPath: '/owner-login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmail-assistant': {
      id: '/gmail-assistant'
      path: '/gmail-assistant'
      fullPath: '/gmail-assistant'
      preLoaderRoute: typeof GmailAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alphabet': {
      id: '/alphabet'
      path: '/alphabet'
      fullPath: '/alphabet'
      preLoaderRoute: typeof AlphabetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/scattergories/$roomId': {
      id: '/scattergories/$roomId'
      path: '/$roomId'
      fullPath: '/scattergories/$roomId'
      preLoaderRoute: typeof ScattergoriesRoomIdRouteImport
      parentRoute: typeof ScattergoriesRoute
    }
    '/game/$roomId': {
      id: '/game/$roomId'
      path: '/game/$roomId'
      fullPath: '/game/$roomId'
      preLoaderRoute: typeof GameRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/tier-board': {
      id: '/books/tier-board'
      path: '/tier-board'
      fullPath: '/books/tier-board'
      preLoaderRoute: typeof BooksTierBoardRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/settings': {
      id: '/books/settings'
      path: '/settings'
      fullPath: '/books/settings'
      preLoaderRoute: typeof BooksSettingsRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/recommendations': {
      id: '/books/recommendations'
      path: '/recommendations'
      fullPath: '/books/recommendations'
      preLoaderRoute: typeof BooksRecommendationsRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/library': {
      id: '/books/library'
      path: '/library'
      fullPath: '/books/library'
      preLoaderRoute: typeof BooksLibraryRouteImport
      parentRoute: typeof BooksRoute
    }
  }
}

interface BooksRouteChildren {
  BooksLibraryRoute: typeof BooksLibraryRoute
  BooksRecommendationsRoute: typeof BooksRecommendationsRoute
  BooksSettingsRoute: typeof BooksSettingsRoute
  BooksTierBoardRoute: typeof BooksTierBoardRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksLibraryRoute: BooksLibraryRoute,
  BooksRecommendationsRoute: BooksRecommendationsRoute,
  BooksSettingsRoute: BooksSettingsRoute,
  BooksTierBoardRoute: BooksTierBoardRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface ScattergoriesRouteChildren {
  ScattergoriesRoomIdRoute: typeof ScattergoriesRoomIdRoute
}

const ScattergoriesRouteChildren: ScattergoriesRouteChildren = {
  ScattergoriesRoomIdRoute: ScattergoriesRoomIdRoute,
}

const ScattergoriesRouteWithChildren = ScattergoriesRoute._addFileChildren(
  ScattergoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlphabetRoute: AlphabetRoute,
  BooksRoute: BooksRouteWithChildren,
  GmailAssistantRoute: GmailAssistantRoute,
  OwnerLoginRoute: OwnerLoginRoute,
  ScattergoriesRoute: ScattergoriesRouteWithChildren,
  GameRoomIdRoute: GameRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
